name: Build & Tag

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: action-minver-refreshed
      id: version
      uses: Stelzi79/action-minver@3.0.1
      with:
        minver-version: 4.3.0

    - name: echo version #version major minor patch prerelease
      run: |
        echo Version: ${{ steps.version.outputs.version }}
        echo major: ${{ steps.version.outputs.major }}, minor: ${{ steps.version.outputs.minor }}, patch: ${{ steps.version.outputs.patch }}
        echo prerelease: ${{ steps.version.outputs.prerelease }}

    # - name: Latest tag
    #   uses: EndBug/latest-tag@v1.5.1

    - name: Version tag
      uses: EndBug/latest-tag@v1.5.1
      with:
        ref: v${{ steps.version.outputs.version }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6
        dotnet-quality: ga

    #- run: dotnet tool install --global minver-cli --version 4.3.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      cosmos:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
        ports:
          - 8081:8081
          - 10250-10255:10250-10255
        env:
          AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 3
          AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: dotnet build

    - name: Wait for Cosmos Emulator
      uses: cygnetdigital/wait_for_response@v2.0.0
      with:
        url: 'https://localhost:8081/_explorer/index.html'
        responseCode: '200,500'
        timeout: 5000
        interval: 500

    - name: Test
      run: dotnet test --no-build --verbosity normal
