name: Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  ArtifactDirectory: ${{ github.workspace }}/artifacts

defaults:
  run:
    shell: pwsh

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - tag
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        if: false
        with:
          type: 'tar'
          filename: '${{ env.artifactdirectory }}/${{ needs.tag.outputs.version }}.tar.gz'
          exclusions: '*.git* /*node_modules/* .editorconfig *.tar.gz'

      - run: dotnet pack -c Release -o ${{ env.artifactdirectory }} --include-source --include-symbols

      - name: Create GitHub release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.version }}
          artifacts: "${{ env.artifactdirectory }}/*"
          #bodyFile: "body.md"
    