name: Tag

on:
  workflow_call:
    outputs:
      version:
        description: "Generated version"
        value: ${{ jobs.tag.outputs.version }}

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: action-minver-refreshed
      id: version
      uses: Stelzi79/action-minver@3.0.1
      with:
        minver-version: 4.3.0

    - name: echo version #version major minor patch prerelease
      run: |
        echo Version: ${{ steps.version.outputs.version }}
        echo major: ${{ steps.version.outputs.major }}, minor: ${{ steps.version.outputs.minor }}, patch: ${{ steps.version.outputs.patch }}
        echo prerelease: ${{ steps.version.outputs.prerelease }}

    # - name: Latest tag
    #   uses: EndBug/latest-tag@v1.5.1

    - name: Version tag
      uses: EndBug/latest-tag@v1.5.1
      with:
        ref: v${{ steps.version.outputs.version }}