name: Tag

on:
  workflow_call:
    outputs:
      version:
        description: "Generated version"
        value: ${{ jobs.tag.outputs.version }}
      major:
        description: "Generated major version"
        value: ${{ jobs.tag.outputs.major }}
      minor:
        description: "Generated minor version"
        value: ${{ jobs.tag.outputs.minor }}
      patch:
        description: "Generated patch version"
        value: ${{ jobs.tag.outputs.patch }}
      prerelease:
        description: "Generated prerelease version"
        value: ${{ jobs.tag.outputs.prerelease }}

env:
  #MinVerIgnoreHeight: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      major: ${{ steps.version.outputs.major }}
      minor: ${{ steps.version.outputs.minor }}
      patch: ${{ steps.version.outputs.patch }}
      prerelease: ${{ steps.version.outputs.prerelease }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: action-minver-refreshed
      id: version
      uses: Stelzi79/action-minver@3.0.1
      with:
        minver-version: 4.3.0
        auto-increment: patch
        tag-prefix: v
        default-pre-release-phase: preview

    - name: echo version #version major minor patch prerelease
      run: |
        echo Version: ${{ steps.version.outputs.version }}
        echo major: ${{ steps.version.outputs.major }}, minor: ${{ steps.version.outputs.minor }}, patch: ${{ steps.version.outputs.patch }}
        echo prerelease: ${{ steps.version.outputs.prerelease }}
    
    # - run: |
    #     git tag v${{ steps.version.outputs.version }}
    #     git push --tags

    # Update unstable tag on main branch
    - name: unstable tag
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: EndBug/latest-tag@v1.5.1
      with:
        ref: unstable

    # Update latest tag on main branch when tagged RTM
    - name: latest tag
      if: ${{ github.ref == 'refs/heads/main' && steps.version.outputs.prerelease == '' }}
      uses: EndBug/latest-tag@v1.5.1

    # - name: Version tag
    #   uses: EndBug/latest-tag@v1.5.1
    #   with:
    #     ref: v${{ steps.version.outputs.version }}

    # Let's pretend this was a meaningful change