name: Tag & Release

on:
  workflow_call:
  # workflow_dispatch:
  # push:
  #   tags:
  #     - '*'
  #   branches:
  #     - '*'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  ArtifactDirectory: ${{ github.workspace }}/artifacts

defaults:
  run:
    shell: pwsh

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: action-minver-refreshed
      id: version
      uses: Stelzi79/action-minver@3.0.1
      with:
        minver-version: 4.3.0

    - name: echo version #version major minor patch prerelease
      run: |
        echo Version: ${{ steps.version.outputs.version }}
        echo major: ${{ steps.version.outputs.major }}, minor: ${{ steps.version.outputs.minor }}, patch: ${{ steps.version.outputs.patch }}
        echo prerelease: ${{ steps.version.outputs.prerelease }}

    # - name: Latest tag
    #   uses: EndBug/latest-tag@v1.5.1

    - name: Version tag
      uses: EndBug/latest-tag@v1.5.1
      with:
        ref: v${{ steps.version.outputs.version }}

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - tag
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'tar'
          filename: '${{ env.artifactdirectory }}/${{ needs.tag.outputs.version }}.tar.gz'
          exclusions: '*.git* /*node_modules/* .editorconfig *.tar.gz'

      - run: dotnet pack -c Release -o ${{ env.artifactdirectory }} --include-source --include-symbols

      - name: Create GitHub release
        id: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.artifactdirectory }}/*"
          #bodyFile: "body.md"
    